using MetBench_BLL.SystemMT.Assertions;
using MetBench_BLL.SystemMT.Pipeline;
using MetBench_SystemMT.Tests.SystemMT;
using Reqnroll;
using Xunit;

namespace MetBench_SystemMT.Tests.Steps;

[Binding]
public sealed class ProjectileRangeSteps
{
    private string? _sourceInputPath;
    private string _workRoot = string.Empty;
    private PipelineOutcome? _outcome;

    [Given("a projectile MT case named {string} with input {string}")]
    public async Task GivenAProjectileMtCase(string caseName, string inputLine)
    {
        if (caseName.Equals("source", StringComparison.OrdinalIgnoreCase))
        {
            _workRoot = Path.Combine(Path.GetTempPath(), "MetBenchProjectileBdd", Guid.NewGuid().ToString("N"));
            var caseDir = Path.Combine(_workRoot, caseName);
            Directory.CreateDirectory(caseDir);

            _sourceInputPath = Path.Combine(caseDir, "input.txt");
            await File.WriteAllTextAsync(_sourceInputPath, inputLine, CancellationToken.None);
        }
        // follow-up case is generated by the pipeline (ScaleField on /v0 with factor=2)
    }

    [When("I run both projectile cases")]
    public async Task WhenIRunBothProjectileCases()
    {
        Assert.NotNull(_sourceInputPath);

        var assetRoot = TestAssetPaths.AssetRoot();
        var python = TestAssetPaths.PythonExecutable();
        var projectileDir = Path.Combine(assetRoot, "projectile");

        // Doubling v0 quadruples range (R 鈭?v0虏)
        var ctx = new PipelineContext(
            MrCode: "bdd-projectile-scale-v0",
            TransformationName: "ScaleField",
            AssertionTypeCode: "greater",
            ValueName: "range",
            TargetFieldPath: "/v0",
            PathSyntax: "json-pointer",
            Parameters: new Dictionary<string, string> { ["factor"] = "2" },
            Tolerance: new AssertionTolerance(),
            ExtraAssertionValues: null,
            SutName: "projectile",
            SourceCasePath: _sourceInputPath!,
            WorkingDirectory: _workRoot,
            InputParserInvocation: new ProcessInvocation(python, new[] { Path.Combine(projectileDir, "projectile_input_parser.py") }),
            OutputParserInvocation: new ProcessInvocation(python, new[] { Path.Combine(projectileDir, "projectile_output_parser.py") }),
            RunnerInvocation: new ProcessInvocation(python, new[] { Path.Combine(projectileDir, "projectile.py") }),
            TimeoutSeconds: 10,
            CatalogVersionSha: string.Empty,
            SutVersionSnapshot: string.Empty,
            MetbenchVersion: string.Empty,
            TriggeredBy: "bdd");

        _outcome = await new SystemMtPipeline().ExecuteAsync(ctx, cancellationToken: CancellationToken.None);
    }

    [Then("the projectile parsed value {string} of {string} should exceed {string}")]
    public void ThenProjectileParsedValueShouldExceed(
        string valueName,
        string followUpCaseName,
        string sourceCaseName)
    {
        Assert.NotNull(_outcome);
        Assert.Equal("range", valueName);
        Assert.Equal("follow-up", followUpCaseName);
        Assert.Equal("source", sourceCaseName);
        Assert.True(_outcome!.AssertionResult?.Passed ?? false,
            _outcome.AssertionResult?.FailureReason ?? _outcome.ErrorMessage);
    }

    [Then("the follow-up range should be approximately {int} times the source range")]
    public void ThenFollowUpRangeRatio(int expectedRatio)
    {
        Assert.NotNull(_outcome);
        var sourceRange = _outcome!.SourceMetrics!["range"];
        var followUpRange = _outcome.FollowupMetrics!["range"];
        var ratio = followUpRange / sourceRange;
        Assert.InRange(ratio, expectedRatio - 0.01, expectedRatio + 0.01);
    }
}
