using MetBench_BLL.SystemMT.Assertions;
using MetBench_BLL.SystemMT.Pipeline;
using MetBench_SystemMT.Tests.SystemMT;
using Reqnroll;
using Xunit;

namespace MetBench_SystemMT.Tests.Steps;

[Binding]
public sealed class SystemLevelCliMtSteps
{
    private string? _sourceInputPath;
    private string _workRoot = string.Empty;
    private PipelineOutcome? _outcome;

    [Given("a system MT case named {string} with input file {string}")]
    public async Task GivenASystemMtCaseNamedWithInputFile(string caseName, string inputFile)
    {
        if (caseName.Equals("source", StringComparison.OrdinalIgnoreCase))
        {
            var caseDir = Path.Combine(Path.GetTempPath(), "MetBenchSystemMtBdd", Guid.NewGuid().ToString("N"), caseName);
            Directory.CreateDirectory(caseDir);
            _workRoot = Path.GetDirectoryName(caseDir)!;

            var inputPath = Path.Combine(caseDir, inputFile);
            await File.WriteAllTextAsync(inputPath, "3", CancellationToken.None);
            _sourceInputPath = inputPath;
        }
        // follow-up case is generated by the pipeline; ignore explicit setup
    }

    [When("I run both cases with program profile {string}")]
    public async Task WhenIRunBothCasesWithProgramProfile(string profileName)
    {
        Assert.Equal("example-cli", profileName);
        Assert.NotNull(_sourceInputPath);

        var assetRoot = TestAssetPaths.AssetRoot();
        var python = TestAssetPaths.PythonExecutable();

        var ctx = new PipelineContext(
            MrCode: "bdd-example-cli-greater-than",
            TransformationName: "ScaleField",
            AssertionTypeCode: "greater",
            ValueName: "result",
            TargetFieldPath: "/value",
            PathSyntax: "json-pointer",
            Parameters: new Dictionary<string, string> { ["factor"] = "3" },
            Tolerance: new AssertionTolerance(),
            ExtraAssertionValues: null,
            SutName: "example-cli",
            SourceCasePath: _sourceInputPath!,
            WorkingDirectory: _workRoot,
            InputParserInvocation: new ProcessInvocation(python, new[] { Path.Combine(assetRoot, "example_cli_input_parser.py") }),
            OutputParserInvocation: new ProcessInvocation(python, new[] { Path.Combine(assetRoot, "example_cli_output_parser.py") }),
            RunnerInvocation: new ProcessInvocation(python, new[] { Path.Combine(assetRoot, "example_cli.py") }),
            TimeoutSeconds: 10,
            CatalogVersionSha: string.Empty,
            SutVersionSnapshot: string.Empty,
            MetbenchVersion: string.Empty,
            TriggeredBy: "bdd");

        _outcome = await new SystemMtPipeline().ExecuteAsync(ctx, cancellationToken: CancellationToken.None);
    }

    [Then("the parsed output value {string} of {string} should be greater than {string}")]
    public void ThenTheParsedOutputValueOfShouldBeGreaterThan(
        string valueName,
        string followUpCaseName,
        string sourceCaseName)
    {
        Assert.NotNull(_outcome);
        Assert.Equal("result", valueName);
        Assert.Equal("follow-up", followUpCaseName);
        Assert.Equal("source", sourceCaseName);
        Assert.True(_outcome!.AssertionResult?.Passed ?? false,
            _outcome.AssertionResult?.FailureReason ?? _outcome.ErrorMessage);
    }
}
