<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>MetBench_DAL</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU;x86;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LiteDB" Version="5.0.21" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="4.7.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MetBench_BLL.Core\MetBench_BLL.Core.csproj" />
    <ProjectReference Include="..\MetBench_Domain\MetBench_Domain.csproj" />
    <ProjectReference Include="..\MetBench_IDAL\MetBench_IDAL.csproj" />
  </ItemGroup>

</Project>
