<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU;x86;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.0.0" />
    <PackageReference Include="FluentAssertions" Version="6.12.0" />
    <PackageReference Include="MathNet.Numerics" Version="5.0.0" />
    <PackageReference Include="YamlDotNet" Version="16.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MetBench_Domain\MetBench_Domain.csproj" />
    <ProjectReference Include="..\MetBench_IDAL\MetBench_IDAL.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="MetBench_SystemMT.Tests" />
  </ItemGroup>

</Project>
