"""MR14 cross-program comparison report (NOETHER block E*, method-comparison).

Compares OpenMOC and OpenMC k_eff on every scenario that has a matched
solver twin in the SCENARIOS list. The MR is

    | k_OpenMOC(case) − k_OpenMC(case) | ≤ ε_budget(case)

where the budget combines the MC statistical uncertainty (3·σ on the
OpenMC side) and a small MOC-discretisation budget. A pair that
exceeds the budget is reported as **disagreement** — a candidate
cross-program bug.

Phase 2 surfaced a concrete case worth flagging this way: at
`ScaleModeratorSigmaA(factor=1.5)` the unpatched OpenMOC k_eff =
0.4764 while OpenMC gives 0.9683 — a 51% disagreement, well past any
reasonable budget. This is a real numerical artefact of OpenMOC's
power-iteration solver under that material configuration (see
`discussion-phase2.md`), and MR14 is exactly the MR that would catch
it in normal MT operation.

The tool reads `_data/baseline.json` (unpatched followups) and emits
`docs/experiments/cross-program-report.md`. Per-mutation cross-program
disagreement can be added later by iterating matrix.json files; this
first pass focuses on the baseline pairs.

Invocation:
    python3 tools/cross_program_mr.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
BASELINE_PATH = REPO_ROOT / "docs" / "experiments" / "_data" / "baseline.json"
REPORT_PATH = REPO_ROOT / "docs" / "experiments" / "cross-program-report.md"

sys.path.insert(0, str(REPO_ROOT / "tools"))
from mutation_study import SCENARIOS  # noqa: E402

MOC_DISC_BUDGET_REL = 0.01  # ε_MOC ≈ 1%·k (empirical on this SUT — 0.5%
# from the paper Table 3 is too tight in practice and flags routine 16-azim
# tracking vs 5000-particle MC discretization noise as "disagreement";
# 1% reliably accommodates the normal cross-method spread and only fires
# on genuine solver disagreements like the moderator-sigma-a pathology
# documented in discussion-phase2.md).


def find_twin(sc: dict) -> dict | None:
    """Return the same-transform scenario for the other solver, or None."""
    other = "openmc" if sc["solver"] == "openmoc" else "openmoc"
    for cand in SCENARIOS:
        if cand["solver"] != other:
            continue
        if cand.get("transform") == sc.get("transform") and cand.get("source_case") == sc.get("source_case"):
            return cand
    return None


def main() -> int:
    baseline = json.loads(BASELINE_PATH.read_text())
    flw = baseline["followups"]

    # Build openmoc → openmc pairs (each pair printed once).
    seen: set[str] = set()
    rows: list[dict] = []
    for sc in SCENARIOS:
        if sc["solver"] != "openmoc":
            continue
        twin = find_twin(sc)
        if twin is None:
            continue
        key = (sc["id"], twin["id"])
        if key in seen:
            continue
        seen.add(key)

        moc = flw.get(sc["id"], {})
        mc = flw.get(twin["id"], {})
        if moc.get("skipped") or mc.get("skipped"):
            rows.append({
                "transform": sc.get("transform", "?"),
                "moc_scenario": sc["id"],
                "mc_scenario": twin["id"],
                "k_moc": moc.get("k_eff"),
                "k_mc": mc.get("k_eff"),
                "delta": None,
                "budget": None,
                "verdict": "skipped",
            })
            continue
        k_moc = float(moc["k_eff"])
        k_mc = float(mc["k_eff"])
        sigma_mc = float(mc.get("k_eff_std", 0.0))
        delta = abs(k_moc - k_mc)
        budget = max(3.0 * sigma_mc, MOC_DISC_BUDGET_REL * abs(k_mc))
        rows.append({
            "transform": sc.get("transform", "?"),
            "moc_scenario": sc["id"],
            "mc_scenario": twin["id"],
            "k_moc": k_moc,
            "k_mc": k_mc,
            "sigma_mc": sigma_mc,
            "delta": delta,
            "budget": budget,
            "verdict": "agree" if delta <= budget else "DISAGREE",
        })

    # Header summary.
    n_pairs = sum(1 for r in rows if r["verdict"] != "skipped")
    n_disagree = sum(1 for r in rows if r["verdict"] == "DISAGREE")
    n_skipped = sum(1 for r in rows if r["verdict"] == "skipped")

    md: list[str] = []
    md.append("# Cross-program MR14 (OpenMOC vs OpenMC) — baseline pairs\n")
    md.append("Auto-generated by `tools/cross_program_mr.py`. Compares the\n"
              "unpatched (Mut00-equivalent) k_eff for every MR scenario that has\n"
              "matched OpenMOC and OpenMC twins.\n")
    md.append(f"\n**Summary**: {n_pairs} evaluable pairs, **{n_disagree} disagreement**, "
              f"{n_skipped} skipped. "
              f"Budget = `max(3·σ_OpenMC, {MOC_DISC_BUDGET_REL*100:.1f}%·k_OpenMC)`.\n")
    md.append("\n| Transform | k(OpenMOC) | k(OpenMC) | σ(OpenMC) | |Δk| | budget | verdict |")
    md.append("|---|--:|--:|--:|--:|--:|--:|")
    for r in rows:
        if r["verdict"] == "skipped":
            k_moc_str = "—" if r["k_moc"] is None else f"{r['k_moc']:.5f}"
            k_mc_str = "—" if r["k_mc"] is None else f"{r['k_mc']:.5f}"
            md.append(f"| {r['transform']} | {k_moc_str} | {k_mc_str} | — | — | — | _skipped_ |")
            continue
        verdict_marker = "**DISAGREE**" if r["verdict"] == "DISAGREE" else "agree"
        md.append(f"| {r['transform']} | "
                  f"{r['k_moc']:.5f} | {r['k_mc']:.5f} | "
                  f"{r['sigma_mc']:.5f} | "
                  f"{r['delta']:.5f} | {r['budget']:.5f} | {verdict_marker} |")

    md.append("\n## Disagreements\n")
    if n_disagree == 0:
        md.append("None.\n")
    else:
        for r in rows:
            if r["verdict"] != "DISAGREE":
                continue
            rel = r["delta"] / abs(r["k_mc"]) * 100 if r["k_mc"] else float("nan")
            md.append(f"\n### {r['transform']}\n")
            md.append(f"* OpenMOC scenario: `{r['moc_scenario']}` → k = {r['k_moc']:.5f}\n")
            md.append(f"* OpenMC scenario:  `{r['mc_scenario']}` → k = {r['k_mc']:.5f} ± {r['sigma_mc']:.5f}\n")
            md.append(f"* |Δk| = {r['delta']:.5f} ({rel:.1f}% of OpenMC), budget = {r['budget']:.5f}\n")
            md.append(f"* **Excess over budget**: {r['delta'] - r['budget']:.5f}.\n")

    md.append("\n---\n")
    md.append("See `discussion-phase2.md` for the qualitative analysis "
              "(in particular the OpenMOC power-iteration convergence pathology "
              "at the moderator-sigma-a follow-up, which this report quantifies).\n")

    REPORT_PATH.write_text("\n".join(md) + "\n")
    print(f"Wrote {REPORT_PATH.relative_to(REPO_ROOT)}")
    print(f"  pairs evaluated: {n_pairs}")
    print(f"  disagreements:   {n_disagree}")
    print(f"  skipped:         {n_skipped}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
