"""MR14 cross-program comparison report (NOETHER block E*, method-comparison).

Compares OpenMOC and OpenMC k_eff on every scenario that has a matched
solver twin in the SCENARIOS list. The MR is

    | k_OpenMOC(case) − k_OpenMC(case) | ≤ ε_budget(case)

where the budget combines the MC statistical uncertainty (3·σ on the
OpenMC side) and a small MOC-discretisation budget. A pair that
exceeds the budget is reported as **disagreement** — a candidate
cross-program bug.

Phase 2 surfaced a concrete case worth flagging this way: at
`ScaleModeratorSigmaA(factor=1.5)` the unpatched OpenMOC k_eff =
0.4764 while OpenMC gives 0.9683 — a 51% disagreement, well past any
reasonable budget. This is a real numerical artefact of OpenMOC's
power-iteration solver under that material configuration (see
`discussion-phase2.md`), and MR14 is exactly the MR that would catch
it in normal MT operation.

The tool reads `_data/baseline.json` (unpatched followups) and emits
`docs/experiments/cross-program-report.md`. Per-mutation cross-program
disagreement can be added later by iterating matrix.json files; this
first pass focuses on the baseline pairs.

Invocation:
    python3 tools/cross_program_mr.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
BASELINE_PATH = REPO_ROOT / "docs" / "experiments" / "_data" / "baseline.json"
CANDIDATES_DIR = REPO_ROOT / "docs" / "experiments" / "_data" / "candidates"
REPORT_PATH = REPO_ROOT / "docs" / "experiments" / "cross-program-report.md"

sys.path.insert(0, str(REPO_ROOT / "tools"))
from mutation_study import SCENARIOS, MATCHED_PAIRS  # noqa: E402

MOC_DISC_BUDGET_REL = 0.01  # ε_MOC ≈ 1%·k (empirical on this SUT — 0.5%
# from the paper Table 3 is too tight in practice and flags routine 16-azim
# tracking vs 5000-particle MC discretization noise as "disagreement";
# 1% reliably accommodates the normal cross-method spread and only fires
# on genuine solver disagreements like the moderator-sigma-a pathology
# documented in discussion-phase2.md).


def find_twin(sc: dict) -> dict | None:
    """Return the same-transform scenario for the other solver, or None."""
    other = "openmc" if sc["solver"] == "openmoc" else "openmoc"
    for cand in SCENARIOS:
        if cand["solver"] != other:
            continue
        if cand.get("transform") == sc.get("transform") and cand.get("source_case") == sc.get("source_case"):
            return cand
    return None


def main() -> int:
    baseline = json.loads(BASELINE_PATH.read_text())
    flw = baseline["followups"]

    # Build openmoc → openmc pairs (each pair printed once).
    seen: set[str] = set()
    rows: list[dict] = []
    for sc in SCENARIOS:
        if sc["solver"] != "openmoc":
            continue
        twin = find_twin(sc)
        if twin is None:
            continue
        key = (sc["id"], twin["id"])
        if key in seen:
            continue
        seen.add(key)

        moc = flw.get(sc["id"], {})
        mc = flw.get(twin["id"], {})
        if moc.get("skipped") or mc.get("skipped"):
            rows.append({
                "transform": sc.get("transform", "?"),
                "moc_scenario": sc["id"],
                "mc_scenario": twin["id"],
                "k_moc": moc.get("k_eff"),
                "k_mc": mc.get("k_eff"),
                "delta": None,
                "budget": None,
                "verdict": "skipped",
            })
            continue
        k_moc = float(moc["k_eff"])
        k_mc = float(mc["k_eff"])
        sigma_mc = float(mc.get("k_eff_std", 0.0))
        delta = abs(k_moc - k_mc)
        budget = max(3.0 * sigma_mc, MOC_DISC_BUDGET_REL * abs(k_mc))
        rows.append({
            "transform": sc.get("transform", "?"),
            "moc_scenario": sc["id"],
            "mc_scenario": twin["id"],
            "k_moc": k_moc,
            "k_mc": k_mc,
            "sigma_mc": sigma_mc,
            "delta": delta,
            "budget": budget,
            "verdict": "agree" if delta <= budget else "DISAGREE",
        })

    # Header summary.
    n_pairs = sum(1 for r in rows if r["verdict"] != "skipped")
    n_disagree = sum(1 for r in rows if r["verdict"] == "DISAGREE")
    n_skipped = sum(1 for r in rows if r["verdict"] == "skipped")

    md: list[str] = []
    md.append("# Cross-program MR14 (OpenMOC vs OpenMC) — baseline pairs\n")
    md.append("Auto-generated by `tools/cross_program_mr.py`. Compares the\n"
              "unpatched (Mut00-equivalent) k_eff for every MR scenario that has\n"
              "matched OpenMOC and OpenMC twins.\n")
    md.append(f"\n**Summary**: {n_pairs} evaluable pairs, **{n_disagree} disagreement**, "
              f"{n_skipped} skipped. "
              f"Budget = `max(3·σ_OpenMC, {MOC_DISC_BUDGET_REL*100:.1f}%·k_OpenMC)`.\n")
    md.append("\n| Transform | k(OpenMOC) | k(OpenMC) | σ(OpenMC) | |Δk| | budget | verdict |")
    md.append("|---|--:|--:|--:|--:|--:|--:|")
    for r in rows:
        if r["verdict"] == "skipped":
            k_moc_str = "—" if r["k_moc"] is None else f"{r['k_moc']:.5f}"
            k_mc_str = "—" if r["k_mc"] is None else f"{r['k_mc']:.5f}"
            md.append(f"| {r['transform']} | {k_moc_str} | {k_mc_str} | — | — | — | _skipped_ |")
            continue
        verdict_marker = "**DISAGREE**" if r["verdict"] == "DISAGREE" else "agree"
        md.append(f"| {r['transform']} | "
                  f"{r['k_moc']:.5f} | {r['k_mc']:.5f} | "
                  f"{r['sigma_mc']:.5f} | "
                  f"{r['delta']:.5f} | {r['budget']:.5f} | {verdict_marker} |")

    md.append("\n## Disagreements\n")
    if n_disagree == 0:
        md.append("None.\n")
    else:
        for r in rows:
            if r["verdict"] != "DISAGREE":
                continue
            rel = r["delta"] / abs(r["k_mc"]) * 100 if r["k_mc"] else float("nan")
            md.append(f"\n### {r['transform']}\n")
            md.append(f"* OpenMOC scenario: `{r['moc_scenario']}` → k = {r['k_moc']:.5f}\n")
            md.append(f"* OpenMC scenario:  `{r['mc_scenario']}` → k = {r['k_mc']:.5f} ± {r['sigma_mc']:.5f}\n")
            md.append(f"* |Δk| = {r['delta']:.5f} ({rel:.1f}% of OpenMC), budget = {r['budget']:.5f}\n")
            md.append(f"* **Excess over budget**: {r['delta'] - r['budget']:.5f}.\n")

    md.append("\n---\n")
    md.append("See `discussion-phase2.md` for the qualitative analysis "
              "(in particular the OpenMOC power-iteration convergence pathology "
              "at the moderator-sigma-a follow-up, which this report quantifies).\n")

    # -------------------------------------------------------------------
    # Per-matched-pair MR14: same logical bug applied to both solvers,
    # compare k_followup of (OpenMOC mutant, OpenMC twin) cells.
    # -------------------------------------------------------------------
    md.append("\n# Per-matched-pair MR14 (mutated follow-up agreement)\n")
    md.append("\nFor each matched-pair index (`MATCHED_PAIRS` in "
              "`mutation_study.py`), compares the follow-up k_eff of the OpenMOC "
              "mutant against its OpenMC twin on the corresponding MR scenario. "
              "Same MR, same logical bug, both solvers — disagreement signals a "
              "fault class that bites the two solvers asymmetrically.\n")
    md.append(f"\nBudget rule unchanged: `max(3·σ_OpenMC, {MOC_DISC_BUDGET_REL*100:.1f}%·k_OpenMC)`.\n")

    # Add Mut00 as a virtual pair against itself for a control row.
    pair_rows: list[dict] = []
    pairs_to_check = [("Mut00-identity", "Mut00-identity", "identity-control")]
    pairs_to_check += [(moc, mc, kind) for moc, mc, kind in MATCHED_PAIRS]

    for moc_id, mc_id, kind in pairs_to_check:
        moc_path = CANDIDATES_DIR / moc_id / "matrix.json"
        mc_path = CANDIDATES_DIR / mc_id / "matrix.json"
        if not (moc_path.exists() and mc_path.exists()):
            pair_rows.append({"kind": kind, "moc_mut": moc_id, "mc_mut": mc_id,
                              "scenario": "—", "verdict": "missing-matrix"})
            continue
        moc_data = json.loads(moc_path.read_text())
        mc_data = json.loads(mc_path.read_text())

        # For each transform that has both an openmoc-* and openmc-* scenario,
        # check whether both mutants have a "ran" cell.
        for sc in SCENARIOS:
            if sc["solver"] != "openmoc":
                continue
            twin = find_twin(sc)
            if twin is None:
                continue
            moc_cell = next((c for c in moc_data["cells"] if c["scenario_id"] == sc["id"]), None)
            mc_cell = next((c for c in mc_data["cells"] if c["scenario_id"] == twin["id"]), None)
            if not moc_cell or not mc_cell:
                continue
            if moc_cell.get("status") != "ran" or mc_cell.get("status") != "ran":
                continue
            k_moc = float(moc_cell["k_followup"])
            k_mc = float(mc_cell["k_followup"])
            sigma_mc = float(mc_cell.get("k_followup_std", 0.0) or 0.0)
            if any(map(lambda x: x != x or x in (float("inf"), float("-inf")), (k_moc, k_mc))):
                # NaN or inf — automatically disagreement (pathological)
                pair_rows.append({
                    "kind": kind, "moc_mut": moc_id, "mc_mut": mc_id,
                    "scenario": sc.get("transform", "?"),
                    "k_moc": k_moc, "k_mc": k_mc, "sigma_mc": sigma_mc,
                    "delta": float("nan"), "budget": float("nan"),
                    "verdict": "DISAGREE (pathological NaN/Inf)",
                })
                continue
            delta = abs(k_moc - k_mc)
            budget = max(3.0 * sigma_mc, MOC_DISC_BUDGET_REL * abs(k_mc))
            verdict = "DISAGREE" if delta > budget else "agree"
            pair_rows.append({
                "kind": kind, "moc_mut": moc_id, "mc_mut": mc_id,
                "scenario": sc.get("transform", "?"),
                "k_moc": k_moc, "k_mc": k_mc, "sigma_mc": sigma_mc,
                "delta": delta, "budget": budget, "verdict": verdict,
            })

    pair_disagrees = sum(1 for r in pair_rows if "DISAGREE" in r["verdict"])
    pair_evaluated = sum(1 for r in pair_rows if r["verdict"] not in ("missing-matrix",))
    md.append(f"\n**Summary**: {pair_evaluated} matched-pair-scenario rows, "
              f"**{pair_disagrees} disagreement**.\n")
    md.append("\n| pair kind | scenario (transform) | OpenMOC mut | OpenMC mut | "
              "k(MOC mut) | k(MC mut) | σ(MC) | |Δk| | budget | verdict |")
    md.append("|---|---|---|---|--:|--:|--:|--:|--:|--:|")
    for r in pair_rows:
        if r["verdict"] == "missing-matrix":
            md.append(f"| {r['kind']} | — | {r['moc_mut']} | {r['mc_mut']} | "
                      f"— | — | — | — | — | _matrix.json missing_ |")
            continue
        kmoc = f"{r['k_moc']:.5f}" if r["k_moc"] == r["k_moc"] else "nan"  # NaN-safe
        kmc = f"{r['k_mc']:.5f}" if r["k_mc"] == r["k_mc"] else "nan"
        sig = f"{r['sigma_mc']:.5f}"
        d = f"{r['delta']:.5f}" if r["delta"] == r["delta"] else "nan"
        b = f"{r['budget']:.5f}" if r["budget"] == r["budget"] else "nan"
        marker = "**" + r["verdict"] + "**" if "DISAGREE" in r["verdict"] else "agree"
        md.append(f"| {r['kind']} | {r['scenario']} | {r['moc_mut']} | {r['mc_mut']} | "
                  f"{kmoc} | {kmc} | {sig} | {d} | {b} | {marker} |")

    if pair_disagrees > 0:
        md.append("\n## Per-pair disagreements — interpretation\n")
        for r in pair_rows:
            if "DISAGREE" not in r["verdict"]:
                continue
            md.append(f"\n### {r['kind']} on {r['scenario']}\n")
            md.append(f"* OpenMOC mutant: `{r['moc_mut']}` → k_followup = {r.get('k_moc')}\n")
            md.append(f"* OpenMC mutant:  `{r['mc_mut']}` → k_followup = {r.get('k_mc')} ± {r.get('sigma_mc')}\n")
            if "pathological" in r["verdict"]:
                md.append("* NaN / Inf on at least one side — the bug class drives the\n"
                          "  affected solver into a divergent state. Easy disagreement.\n")
            else:
                md.append(f"* |Δk| = {r['delta']} ; budget = {r['budget']}.\n")

    md.append("\n---\n")
    md.append("See `discussion-phase2.md` for the qualitative analysis. The baseline\n"
              "section above probes the unpatched cross-solver gap (notably the\n"
              "OpenMOC moderator-sigma-a convergence pathology); this section probes\n"
              "whether the SAME logical bug applied to both solvers produces "
              "physically-comparable damage.\n")

    REPORT_PATH.write_text("\n".join(md) + "\n")
    print(f"Wrote {REPORT_PATH.relative_to(REPO_ROOT)}")
    print(f"  baseline pairs evaluated: {n_pairs}, disagreements: {n_disagree}, skipped: {n_skipped}")
    print(f"  matched-pair rows evaluated: {pair_evaluated}, disagreements: {pair_disagrees}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
